### PR TITLE
Move go.mod and go.sum to repo root

### PR DESCRIPTION
**Pull request by martinhpedersen**
Ref https://github.com/n8jja/Pat-Vara/issues/19#issuecomment-1307753063.

Please tag with `v1.0.1` after merge. Not 100% certain that this will work, but I'm unable to test locally 🤞

### CODE REVIEW

**Comment by martinhpedersen** [comment]
Ping @n8jja in case you're still not receiving PR notifications 😊

**Comment by n8jja** [comment]
@martinhpedersen - Done!  And I did get my GitHub messaging fixed.  Thanks!

**Comment by martinhpedersen** [comment]
@n8jja - Hmm.. the new tag [v1.0.1](https://github.com/n8jja/Pat-Vara/releases/tag/v1.0.1) points to [964c774](https://github.com/n8jja/Pat-Vara/commit/964c774eec54d8502363a41097f7edf9e1b71273). This commit does not appear to be part of the main branch. 🤔 

PS: Just keep incrementing PATCH until we get it right. Be careful not to tag a new MAJOR. Ever. Unless you introduce breaking changes, which most Go package maintainers try to avoid. As far as Go Modules is concerned, incrementing MAJOR is the same as forking the entire module. More on that here: https://go.dev/ref/mod#versions.

**Comment by n8jja** [comment]
@martinhpedersen - Maybe now?  SHould be v1.0.2

**Pull request merged**
